name: Publish on Netlify

on: [push, pull_request]
jobs: 
  publish:
    runs-on: ubuntu-20.04

    steps:    
    - uses: actions/checkout@v2

    - name: install
      run: sudo apt update && sudo apt-get install asciidoctor && sudo apt install linkchecker

    - name: Compile
      run: make all
    
    - name: TestURL
      run: linkchecker --check-extern ./dist/index.html 
    
    - name: Publish
      if: ${{ github.event_name == 'push' }}
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod --dir=./dist
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      